# Generated by Django 4.1.1 on 2022-10-08 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "std_id",
                    models.CharField(
                        max_length=10, null=True, verbose_name="Student ID"
                    ),
                ),
                (
                    "std_first",
                    models.CharField(
                        max_length=200, null=True, verbose_name="First Name"
                    ),
                ),
                (
                    "std_last",
                    models.CharField(
                        max_length=200, null=True, verbose_name="Last Name"
                    ),
                ),
                (
                    "b_date",
                    models.DateField(
                        blank=True,
                        help_text="format: YYYY-MM-DD",
                        null=True,
                        verbose_name="Birth Date",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("email", models.CharField(max_length=200, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
