# Generated by Django 4.1.1 on 2022-09-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cname", models.CharField(max_length=100)),
                ("semester", models.IntegerField()),
                ("year", models.IntegerField()),
                ("amount", models.IntegerField(default=0)),
                ("avail", models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name="student",
            name="nationality",
        ),
        migrations.AlterField(
            model_name="student",
            name="slastname",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="student",
            name="sname",
            field=models.CharField(max_length=100),
        ),
    ]
