# Generated by Django 4.1.1 on 2022-09-15 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_course_avail_course_registered_enrollment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Enrollment",
        ),
    ]
