# Generated by Django 4.1.1 on 2022-09-15 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_delete_enrollment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="registered",
        ),
    ]
