# Generated by Django 4.1.1 on 2022-09-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_remove_student_enrolled"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="email",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
