# Generated by Django 4.1.1 on 2022-10-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "c_code",
                    models.CharField(
                        max_length=5, null=True, verbose_name="Course Code"
                    ),
                ),
                (
                    "c_name",
                    models.CharField(
                        max_length=200, null=True, verbose_name="Course Name"
                    ),
                ),
                (
                    "semester",
                    models.PositiveIntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3")], null=True
                    ),
                ),
                ("year", models.CharField(max_length=4, null=True)),
                ("quota", models.PositiveIntegerField(null=True)),
                (
                    "status",
                    models.BooleanField(
                        default=True,
                        help_text="Check = Open, Uncheck = Close",
                        verbose_name="Course Status",
                    ),
                ),
                (
                    "enrolled",
                    models.ManyToManyField(
                        blank=True, related_name="enrolled", to="users.student"
                    ),
                ),
            ],
        ),
    ]
