# Generated by Django 4.1.1 on 2022-09-15 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_alter_course_c_semester"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="std_id",
            field=models.IntegerField(verbose_name="Student ID"),
        ),
    ]
