# Generated by Django 4.1.1 on 2022-09-15 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_alter_student_std_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="c_name",
        ),
        migrations.RemoveField(
            model_name="course",
            name="c_semester",
        ),
        migrations.RemoveField(
            model_name="course",
            name="quota",
        ),
        migrations.RemoveField(
            model_name="course",
            name="status",
        ),
        migrations.RemoveField(
            model_name="course",
            name="year",
        ),
        migrations.AlterField(
            model_name="student",
            name="b_date",
            field=models.DateField(
                blank=True, help_text="format: YYYY-MM-DD", verbose_name="Birth Date"
            ),
        ),
    ]
