# Generated by Django 4.1.1 on 2022-09-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_remove_course_c_name_remove_course_c_semester_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="course",
            field=models.ManyToManyField(
                blank=True, related_name="students", to="courses.course"
            ),
        ),
    ]
