# Generated by Django 4.1.1 on 2022-09-15 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_student_course"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="course",
            name="c_name",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Course Name"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="c_semester",
            field=models.ForeignKey(
                choices=[("one", "1"), ("two", "2"), ("summer", "3")],
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="c_semester",
                to="courses.semester",
                verbose_name="Semester",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="quota",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="course",
            name="status",
            field=models.CharField(
                choices=[("open", "Open"), ("close", "Close")], max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="year",
            field=models.IntegerField(null=True, verbose_name="Year"),
        ),
        migrations.AddField(
            model_name="semester",
            name="year",
            field=models.IntegerField(null=True, verbose_name="Year"),
        ),
        migrations.DeleteModel(
            name="Enroll",
        ),
        migrations.AddField(
            model_name="quota",
            name="course",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="courses.course",
            ),
        ),
        migrations.AddField(
            model_name="quota",
            name="student",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                to="courses.student",
            ),
        ),
    ]
