# Generated by Django 4.1.1 on 2022-09-15 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0006_quota_course_c_name_course_c_semester_course_quota_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="b_date",
            field=models.DateField(
                blank=True,
                help_text="format: YYYY-MM-DD",
                null=True,
                verbose_name="Birth Date",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="std_first",
            field=models.CharField(
                max_length=200, null=True, verbose_name="First Name"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="std_id",
            field=models.IntegerField(null=True, verbose_name="Student ID"),
        ),
        migrations.AlterField(
            model_name="student",
            name="std_last",
            field=models.CharField(max_length=200, null=True, verbose_name="Last Name"),
        ),
    ]
