# Generated by Django 4.1.1 on 2022-09-15 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0007_alter_student_b_date_alter_student_std_first_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="c_semester",
            new_name="semester",
        ),
    ]
