# Generated by Django 4.1.1 on 2022-09-15 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0009_alter_course_semester"),
    ]

    operations = [
        migrations.AlterField(
            model_name="semester",
            name="year",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="std_id",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Student ID",
            ),
        ),
    ]
