# Generated by Django 4.1.1 on 2022-09-15 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0011_student_user_alter_student_std_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="semester",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="c_semester",
                to="courses.semester",
                verbose_name="Semester",
            ),
        ),
    ]
