# Generated by Django 4.1.1 on 2022-09-15 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0012_alter_course_semester"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="semester",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="c_semester",
                to="courses.semester",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="year",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="c_year",
                to="courses.semester",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="course",
            field=models.ManyToManyField(
                blank=True, related_name="student_course", to="courses.course"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
