# Generated by Django 4.1.1 on 2022-09-15 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0013_alter_course_semester_alter_course_year_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="semester",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="c_semester",
                to="courses.semester",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="year",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="c_year",
                to="courses.semester",
            ),
        ),
        migrations.AlterField(
            model_name="semester",
            name="year",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
