# Generated by Django 4.1.1 on 2022-09-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0015_remove_course_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="year",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="quota",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="course",
            name="semester",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="std_id",
            field=models.CharField(max_length=10, null=True, verbose_name="Student ID"),
        ),
        migrations.DeleteModel(
            name="Semester",
        ),
    ]
