# Generated by Django 4.1.1 on 2022-09-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "courses",
            "0016_course_year_alter_course_quota_alter_course_semester_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Semester",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="course",
            name="quota",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="semester",
            field=models.PositiveIntegerField(
                choices=[("one", 1), ("two", 2), ("summer", 3)], null=True
            ),
        ),
    ]
