# Generated by Django 4.1.1 on 2022-09-15 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0017_semester_alter_course_quota_alter_course_semester"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Semester",
        ),
        migrations.AlterField(
            model_name="course",
            name="semester",
            field=models.CharField(
                choices=[('"one"', "1"), ('"two"', "2"), ('"summer"', "3")],
                max_length=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="year",
            field=models.CharField(max_length=4, null=True),
        ),
    ]
