# Generated by Django 4.1.1 on 2022-09-15 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0018_delete_semester_alter_course_semester_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="semester",
            field=models.PositiveIntegerField(
                choices=[(1, "1"), (2, "2"), (3, "3")], null=True
            ),
        ),
    ]
