# Generated by Django 4.1.1 on 2022-09-15 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0019_alter_course_semester"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="status",
            field=models.BooleanField(
                null=True, verbose_name="Check = Open, Uncheck = Close"
            ),
        ),
    ]
