# Generated by Django 4.1.1 on 2022-09-15 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0021_alter_course_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="status",
            field=models.BooleanField(
                default=True,
                verbose_name="Course Status (Check = Open, Uncheck = Close)",
            ),
        ),
    ]
