# Generated by Django 4.1.1 on 2022-09-15 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0022_alter_course_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="c_code",
            field=models.CharField(max_length=5, null=True, verbose_name="Course Code"),
        ),
    ]
