# Generated by Django 4.1.1 on 2022-09-15 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0023_course_c_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="course",
        ),
        migrations.AddField(
            model_name="student",
            name="enrolled",
            field=models.ManyToManyField(
                blank=True, related_name="enrolled", to="courses.course"
            ),
        ),
    ]
