# Generated by Django 4.1.1 on 2022-09-16 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0034_alter_quota_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="b_date",
            field=models.OneToOneField(
                blank=True,
                help_text="format: YYYY-MM-DD",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_b",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Birth Date",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="std_first",
            field=models.OneToOneField(
                max_length=200,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_f",
                to=settings.AUTH_USER_MODEL,
                verbose_name="First Name",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="std_id",
            field=models.OneToOneField(
                max_length=10,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_id",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Student ID",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="std_last",
            field=models.OneToOneField(
                max_length=200,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_l",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Last Name",
            ),
        ),
    ]
