# Generated by Django 4.1.1 on 2022-09-16 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_student_gender"),
        ("courses", "0037_delete_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quota",
            name="student",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                to="users.student",
            ),
        ),
    ]
