# Generated by Django 4.1.1 on 2022-09-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_remove_student_enrolled"),
        ("courses", "0038_alter_quota_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="enrolled",
            field=models.ManyToManyField(
                blank=True, related_name="enrolled", to="users.student"
            ),
        ),
    ]
